// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project Dinô {
  database_type: 'MySQL'
  Note: 'Projeto desenvolvido para o Trabalho de conclusão de curso.'
}

Table bank_account {
  id integer [increment,pk]
  nickname string
  // branch_code = números que representam a agência
  branch_code integer [note: "Pesquisar quantidade de digitos de uma agência bancária"]
  account_number integer [note: "Pesquisar quantidade de digitos de uma conta bancária"]
}

Table pix_key {
  id integer [increment,pk]
  key string
  fk_id_bank_account integer
}
Ref: pix_key.fk_id_bank_account > bank_account.id

Table recurrence_type {
  id integer [increment, pk]
  type string [note: "Mensalmente, Anualmente"]
}

Table amount_received {
  id integer [increment,pk]
  fk_id_recurrence_type integer
  fk_id_value_item integer
  is_recurring bool
}
Ref: amount_received.fk_id_value_item - value_item.id
Ref: amount_received.fk_id_recurrence_type > recurrence_type.id

Table value_item {
  id integer [increment,pk]
  description string
  // gasto está agendado para uma data futura específica
  scheduled_at timestamp
  amount decimal
  fk_id_bank_account integer [note: "Caso seja pago em dinheiro esse atributo será nulo"]
}
Ref: value_item.fk_id_bank_account > bank_account.id

Table expense {
  id integer [increment,pk]
  paid_to string
  fk_id_value_item integer
  fk_id_payment_method integer 
}
Ref: expense.fk_id_value_item - value_item.id
Ref: expense.fk_id_payment_method - payment_method.id

Table credit_card {
  id integer [increment,pk]
  nickname string
  last_four_digits string
  credit_limit decimal
}

/*
Nesse caso pensei o seguinte:
Ao invés de guardar o número de parcelas
Eu poderia ter pagamento à prazo atrelado à um pagamento.
*/

// gasto à prazo
Table installment_expense {
  id integer [increment,pk]
  // número de parcelas
  number_of_installments integer
  fk_id_expense integer
  fk_id_credit_card integer
}
Ref: installment_expense.fk_id_expense - expense.id
Ref: installment_expense.fk_id_credit_card > credit_card.id

Table payment_method_type {
  id integer [increment, pk]
  name string [note: "Ex.: Cartão de Crédito, Pix, Boleto, Transferência Bancária"]
}

Table payment_method {
  id number [increment,pk]
  fk_payment_method_type integer
}

Ref: payment_method.fk_payment_method_type > payment_method_type.id

Table recurring_expense {
  id integer [increment,pk]
  payment_start timestamp
  is_disabled bool [default: false]
  fk_id_recurrence_type integer
  fk_id_expense integer
  fk_id_credit_card integer
}
Ref: recurring_expense.fk_id_expense - expense.id
Ref: recurring_expense.fk_id_credit_card > credit_card.id
Ref: recurring_expense.fk_id_recurrence_type > recurrence_type.id