// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project "Dinô - Update 2" {
  database_type: 'MySQL'
  Note: 'Projeto desenvolvido para o Trabalho de conclusão de curso.'
}

Table value_item {
  id integer [increment,pk]
  description string
  type string [note: "Entrada ou Saída"]
  received_from_OR_paid_to string
  // gasto está agendado para uma data futura específica
  scheduled_at timestamp
  amount decimal
  fk_id_transfer_method integer
}

Ref: value_item.fk_id_transfer_method > transfer_method.id

Table transfer_method {
  id interger [increment, pk]
  fk_id_transfer_method_type integer
}

Table transfer_method_type {
  id integer [increment, pk]
  name string [note: "Ex.: Cartão de Crédito, Pix, Boleto, Transferência Bancária"]
}

Ref: transfer_method.fk_id_transfer_method_type > transfer_method_type.id

Table recurring_value_item {
  id integer [increment, pk]
  is_disabled bool [default: false]
  fk_id_recurrence_type integer
  fk_id_value_item integer
}

Ref: recurring_value_item.fk_id_recurrence_type > recurrence_type.id
Ref: recurring_value_item.fk_id_value_item > value_item.id

Table installment_value_item {
  id integer [increment, pk]
  number_of_installments integer
  fk_id_value_item integer
}

Ref: installment_value_item.fk_id_value_item > value_item.id

Table recurrence_type {
  id integer [increment, pk]
  type string [note: "Mensalmente, Anualmente"]
}

Table bank_account {
  id integer [increment,pk]
  nickname string
  saldo decimal
}

Table bank_account_transfer_method {
  id integer [increment,pk]
  type string [note: "Pix, Débito, Transferência Bancária"]
  fk_id_bank_account integer
}
Ref: bank_account_transfer_method.fk_id_bank_account > bank_account.id


Table value_item_pivot_bank_account_transfer_method {
  fk_id_value_item integer
  fk_id_bank_account_transfer_method integer
}

Ref: value_item_pivot_bank_account_transfer_method.fk_id_value_item > value_item.id
Ref: value_item_pivot_bank_account_transfer_method.fk_id_bank_account_transfer_method > bank_account_transfer_method.id

Table credit_card {
  id integer [increment,pk]
  nickname string
  limit decimal
  last_four_digits string
  // data de fechamento da fatura
  closing_date timestamp
  // data de vencimento da fatura
  due_date timestamp
}

Table value_item_pivot_credit_card_method {
  fk_id_value_item integer
  fk_id_credit_card integer
}

Ref: value_item_pivot_credit_card_method.fk_id_value_item > value_item.id
Ref: value_item_pivot_credit_card_method.fk_id_credit_card > credit_card.id