import Create_UseCase_InstallmentItemValue_FindById from "@src/core/shared/factory_use_case_items/installment_item_value/find_by_id";
const InstallmentPayment_FindById = Create_UseCase_InstallmentItemValue_FindById("Payment")
export default InstallmentPayment_FindById