import Create_UseCase_InstallmentItemValue_Register from "@src/core/shared/factory_use_case_items/installment_item_value/register";
const InstallmentPayment_Register = Create_UseCase_InstallmentItemValue_Register("Payment")
export default InstallmentPayment_Register