import Create_UseCase_InstallmentItemValue_UnmarkAsProcessed from "@src/core/shared/factory_use_case_items/installment_item_value/unmark_as_processed";
const InstallmentPayment_UnmarkAsProcessed = Create_UseCase_InstallmentItemValue_UnmarkAsProcessed("Payment")
export default InstallmentPayment_UnmarkAsProcessed