import Create_UseCase_ItemValue_MarkAsProcessed from "@src/core/shared/factory_use_case_items/item_value/mark_as_processed";
const Receipt_MarkAsProcessed = Create_UseCase_ItemValue_MarkAsProcessed("Receipt")
export default Receipt_MarkAsProcessed