import Create_UseCase_RecurringItemValue_FindById from "@src/core/shared/factory_use_case_items/recurring_item_value/find_by_id";
const RecurringReceipt_FindById = Create_UseCase_RecurringItemValue_FindById("Receipt")
export default RecurringReceipt_FindById