import Create_UseCase_RecurringItemValue_ListAll from "@src/core/shared/factory_use_case_items/recurring_item_value/list_all";
const RecurringReceipt_ListAll = Create_UseCase_RecurringItemValue_ListAll("Receipt")
export default RecurringReceipt_ListAll