import Create_UseCase_RecurringItemValue_MarkAsProcessed from "@src/core/shared/factory_use_case_items/recurring_item_value/mark_as_processed";
const RecurringReceipt_MarkAsProcessed = Create_UseCase_RecurringItemValue_MarkAsProcessed("Receipt")
export default RecurringReceipt_MarkAsProcessed