import Create_UseCase_RecurringItemValue_Update from "@src/core/shared/factory_use_case_items/recurring_item_value/register";
const RecurringReceipt_Update = Create_UseCase_RecurringItemValue_Update("Receipt")
export default RecurringReceipt_Update