import Create_UseCase_InstallmentItemValue_Delete from "@src/core/shared/factory_use_case_items/installment_item_value/delete"
const InstallmentReceipt_Delete = Create_UseCase_InstallmentItemValue_Delete("Receipt")
export default InstallmentReceipt_Delete