import Create_UseCase_InstallmentItemValue_FindById from "@src/core/shared/factory_use_case_items/installment_item_value/find_by_id";
const InstallmentReceipt_FindById = Create_UseCase_InstallmentItemValue_FindById("Receipt")
export default InstallmentReceipt_FindById