import Create_UseCase_InstallmentItemValue_ListAll from "@src/core/shared/factory_use_case_items/installment_item_value/list_all";
const InstallmentReceipt_ListAll = Create_UseCase_InstallmentItemValue_ListAll("Receipt")
export default InstallmentReceipt_ListAll