// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project "Dinô - Update 5" {
  database_type: 'MySQL'
  Note: 'Projeto desenvolvido para o Trabalho de conclusão de curso.'
}

// TABELA PREENCHIDA PELO SISTEMA
Table tag {
  id integer [pk, increment]
  description text [not null, note: "Educação, Saúde, Lazer, Alimentação, Moradia, Transporte, Serviços, Compras, Impostos/Taxas e Outros"]
}

// TABELA PREENCHIDA PELO SISTEMA
Table transfer_method_type {
  id integer [increment, pk]
  name text [not null, note: "Ex.: Pix, Débito, Boleto, Transferência Bancária"]
}

enum item_value_type {
  "Entrada"
  "Saída"
}

Table item_value {
  id integer [pk, increment]
  description text [not null]
  type item_value_type [not null]
  // gasto está agendado para uma data futura específica
  // Ao invés de data seria ideal ter hora e data, mas
  // isso mudaria a forma de como o app funciona
  scheduled_at date [not null]
  amount decimal [not null]
  // Indica se a transferência já foi executada.
  // Se um recebimento foi recebido e se um pagamento foi pago
  was_processed bool [default: `false`, not null]
  fk_id_transfer_method_type integer [not null, ref: > transfer_method_type.id]
  fk_id_tag integer [not null, ref: > tag.id]
  created_at date [default: `(date('now','localtime'))`, not null]
  updated_at date [default: `(date('now','localtime'))`, not null]
}

Table standard_item_value {
  id integer [pk, increment]
  fk_id_item_value integer [not null, ref: - item_value.id]
}

// TABELA PREENCHIDA PELO SISTEMA
Table recurrence_type {
  id integer [increment, pk]
  type text [not null, unique, note: "Mensalmente, Anualmente"]
}

Table recurring {
  id integer [increment, pk]
  is_disabled bool [default: `false`, not null]
  current_amount decimal [not null]
  fk_id_recurrence_type integer [not null, ref: > recurrence_type.id]
}

Table recurring_item_value {
  id integer [increment, pk]
  fk_id_recurring_item_value integer [not null, ref: > recurring.id]
  fk_id_item_value integer [not null, ref: - item_value.id]
}

Table installment {
  id integer [increment, pk]
  installments_number integer [not null]
  total_amount decimal [not null]
}

Table installment_item_value {
  id integer [pk, increment]
  fk_id_installment integer [not null, ref: > installment.id]
  fk_id_item_value integer [not null, ref: - item_value.id]
}

Table bank_account {
  id integer [pk, increment]
  nickname text [not null]
  is_disabled bool [default: `false`, not null]
  // Saldo de uma conta bancária
  balance decimal [not null]
  created_at date [default: `(date('now','localtime'))`, not null]
  update_at date [default: `(date('now','localtime'))`, not null]
}

// TABELA PREENCHIDA PELO SISTEMA
Table bank_account_transfer_method {
  id integer [pk, increment]
  type text [not null, note: "Pix, Débito, Transferência Bancária"]
  is_enable bool [not null]
  fk_id_bank_account integer [not null, ref: > bank_account.id]
  created_at date [default: `(date('now','localtime'))`, not null]
  updated_at date [default: `(date('now','localtime'))`, not null]
}

Table item_value_pivot_bank_account_transfer_method {
  id integer [pk]
  fk_id_item_value integer [not null, ref: - item_value.id]
  fk_id_bank_account_transfer_method integer [not null, ref: > bank_account_transfer_method.id]
}